# Generated by Django 3.0.2 on 2020-02-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
