# Generated by Django 3.0.2 on 2020-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200122_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pet.jpeg', upload_to='profile_pics'),
        ),
    ]
