# Generated by Django 3.0.2 on 2020-05-13 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200324_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 19, 48, 59, 659880)),
        ),
    ]
