# Generated by Django 3.0.2 on 2020-05-14 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200513_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, choices=[('dr', 'Dr.'), ('prof', 'prof.')], max_length=10, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 10, 28, 25, 52983)),
        ),
    ]
