# Generated by Django 3.0.2 on 2020-05-14 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20200514_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 14, 54, 18, 697809)),
        ),
    ]
