# Generated by Django 3.0.2 on 2020-05-14 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20200514_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='title',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 18, 43, 406969)),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Until'),
        ),
        migrations.AddField(
            model_name='booking',
            name='forename',
            field=models.CharField(blank=True, max_length=20, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male.'), ('female', 'Female.')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='booking',
            name='surname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
