# Generated by Django 3.0.2 on 2020-05-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20200514_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(verbose_name='Date booked'),
        ),
    ]
