# Generated by Django 3.0.2 on 2020-05-14 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20200514_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
