# Generated by Django 3.0.2 on 2020-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20200514_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, choices=[('grooming', 'Grooming.'), ('daycare', 'Daycare.'), ('rent_cage', 'Rent_cage.')], max_length=10, verbose_name='Service'),
        ),
    ]
