# Generated by Django 3.0.2 on 2020-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'Cd'))), ('Video', (('vhs', 'Vhs'), ('dvd', 'DVD')))], max_length=30),
        ),
    ]
