# Generated by Django 3.0.2 on 2020-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_auto_20200514_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(blank=True, choices=[('Grooming', (('Dogs Full Bath', 'Dogs Full Bath'), ('Dogs Bath and Haircut', 'Dogs Bath and Haircut'), ('Cats Full Package', 'Cats Full Package'), ('Dogs Full Bath', 'Dogs Full Bath'), ('Pick 3 Spa', 'Pick 3 Spa'), ('Deshedding Service', 'Deshedding Service'), ('Deshedding Deluxe Package', 'Deshedding Deluxe Package'))), ('Pet Boarding', (('boarding', 'Boarding'), ('house sitting', 'House Sitting'), ('pet walking', 'Pet Walking'), ('pet daycare', 'Pet Daycare'), ('drop-in-visit', 'Drop-In-Visit'))), ('Rent_cage', (('cat', 'Cat'), ('dog', 'Dog')))], max_length=30),
        ),
    ]
