# Generated by Django 3.0.2 on 2020-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20200514_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Book From'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Book Until'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='forename',
            field=models.CharField(blank=True, max_length=20, verbose_name='Owner name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male.'), ('female', 'Female.')], max_length=10, verbose_name='Pet Gender'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, choices=[('Grooming', (('Dogs Full Bath', 'Dogs Full Bath'), ('Dogs Bath and Haircut', 'Dogs Bath and Haircut'), ('Cats Full Package', 'Cats Full Package'), ('Dogs Full Bath', 'Dogs Full Bath'), ('Pick 3 Spa', 'Pick 3 Spa'), ('Deshedding Service', 'Deshedding Service'), ('Deshedding Deluxe Package', 'Deshedding Deluxe Package'))), ('Pet Boarding', (('boarding', 'Boarding'), ('house sitting', 'House Sitting'), ('pet walking', 'Pet Walking'), ('pet daycare', 'Pet Daycare'), ('drop-in-visit', 'Drop-In-Visit'))), ('Rent_cage', (('cat', 'Cat'), ('dog', 'Dog')))], max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='surname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pet name'),
        ),
    ]
