# Generated by Django 3.0.2 on 2020-05-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20200514_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.CharField(blank=True, choices=[('basic', 'Basic.'), ('standard', 'Standard.'), ('executive', 'Executive.')], max_length=10, verbose_name='Price Category'),
        ),
    ]
